### ISSUE TITLE
Add labels to plot_cell_indices

### ISSUE THREAD

**Issue by Marius1311** [Marius1311/utility_functions#11]
To the right of the plot, just like in the interactive histograms, would be nice to see the labels corresponding to the annotations from key=''

**Comment by Marius1311** [comment]
And use the color palette saved in adata.uns['key_colors'] if present. So e.g. if you computed a louvain clustering and used this to color in a plot created with scanpy, it will save such color annotation.

**Comment by michalk8** [comment]
Done.
