### ISSUE TITLE
Plotting continious annotations plot_cell_indices

### ISSUE THREAD

**Issue by Marius1311** [Marius1311/utility_functions#15]
I have a time series dataset where each cell is labelled with a time point. Now, when I chose the root cell, I would of course like to chose it from among the cells from the earliest time point. The time information is not categorical, therefore, I get an error: 

AttributeError: Can only use .cat accessor with a 'category' dtype

It would be nice if one could also plot continious annotations.

**Comment by michalk8** [comment]
I've made it that it will convert non categorical data to categorical; please let me know if it works.

**Comment by Marius1311** [comment]
thanks! I will try that.
