### ISSUE TITLE
When creating a cache object, check whether the given path exists

### ISSUE THREAD

**Issue by Marius1311** [Marius1311/utility_functions#18]
Please give some feedback when creating a Cache instance, whether it was sucessful (path found) or not

**Comment by michalk8** [comment]
Done. I added an option (`make_dir=True`) when creating cache. Furthermore, it will warn you now
if the path does not exists or is not a directory.

**Comment by Marius1311** [comment]
cool, perfect! Other than that, I was really impressed by the cache when I tried it yestersay! We should advertise this to the group as well.
