### ISSUE TITLE
Option to group histogram representation by key

### ISSUE THREAD

**Issue by Marius1311** [Marius1311/utility_functions#2]
Often, we want to compare distributions of key quality metrics (like counts dept) accross various batches. For example, the scanpy funciton sc.pl.violin has an option groupby= for this. It would be fantastic to have a similar option in the interactive_histograms functions, so that we get one histogram per batch per quality metric, or two or more histograms with different colors in the same plot.

**Comment by michalk8** [comment]
I've added the grouping, all in one plot, but you can also filter out which groups you're able to see and select their opacity (fill_alpha is by default 0.4).
A small example: selecting groups=['time', 'plate'] will yield 6 groups, if we have 3 plates, in 2 different time points).

**Comment by Marius1311** [comment]
Okay great, thanks!!! I will check it out later. Next time, please in a separate branch and with a PR :)
