### ISSUE TITLE
Add a function that automatically quantifies the batch effect

### ISSUE THREAD

**Issue by Marius1311** [Marius1311/utility_functions#7]
When experimenting with various batch effect removal strategies, it is quite annoying to every time have re-filter for hv genes, compute PCA and KNN and then to look at the UMAP and the PCA. Would be great to have a funciton which takes in an adata object which has somehow been batch corrected and computes how large the batch effect in the given embedding is, using for example the function quant_batch from the utils.py script. Also this function should tell me how much the count depth and n_genes correlated with the first two PC dimensions, using e.g. the function corr_ann from the same script.

**Comment by michalk8** [comment]
Since it's done, I believe we can close this now.
